insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (1, 'Electrolyte Panel', 'Donec ut dolor.', '70 - 100 mg/dL', 929.37, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (2, 'Hemoglobin A1c', 'Nunc rhoncus dui vel sem.', '0.5 - 1.2', 145.4, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (3, 'Thyroid Function', 'In hac habitasse platea dictumst.', '13.5 - 17.5 g/dL', 301.34, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (4, 'Electrolyte Panel', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'Normal', 846.61, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (5, 'Vitamin D Test', 'Proin risus.', '13.5 - 17.5 g/dL', 536.7, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (6, 'Kidney Function Test', 'Nulla suscipit ligula in lacus.', '13.5 - 17.5 g/dL', 651.58, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (7, 'Liver Function Test', 'Cras non velit nec nisi vulputate nonummy.', '13.5 - 17.5 g/dL', 192.04, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (8, 'Vitamin D Test', 'Sed accumsan felis.', '70 - 100 mg/dL', 220.27, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (9, 'Lipid Panel', 'In sagittis dui vel nisl.', '0.5 - 1.2', 610.91, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (10, 'Electrolyte Panel', 'In hac habitasse platea dictumst.', '70 - 100 mg/dL', 541.13, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (11, 'Kidney Function Test', 'In blandit ultrices enim.', '3.5 - 5.0', 253.94, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (12, 'Hemoglobin A1c', 'Curabitur at ipsum ac tellus semper interdum.', '0.5 - 1.2', 765.02, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (13, 'Urinalysis', 'Cras pellentesque volutpat dui.', 'Negative', 528.97, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (14, 'Urinalysis', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '0.5 - 1.2', 194.21, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (15, 'Complete Blood Count', 'Quisque ut erat.', '3.5 - 5.0', 285.13, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (16, 'Liver Function Test', 'Morbi non quam nec dui luctus rutrum.', '3.5 - 5.0', 644.0, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (17, 'Urinalysis', 'Vivamus vel nulla eget eros elementum pellentesque.', 'Normal', 677.86, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (18, 'Urinalysis', 'Integer ac neque.', 'Negative', 810.53, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (19, 'Urinalysis', 'Morbi quis tortor id nulla ultrices aliquet.', '0.5 - 1.2', 619.44, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (20, 'Thyroid Function', 'In eleifend quam a odio.', 'Normal', 176.81, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (21, 'Complete Blood Count', 'Phasellus sit amet erat.', '0.5 - 1.2', 824.57, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (22, 'Liver Function Test', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '13.5 - 17.5 g/dL', 612.29, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (23, 'Complete Blood Count', 'Etiam pretium iaculis justo.', '3.5 - 5.0', 798.32, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (24, 'Urinalysis', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Negative', 861.67, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (25, 'Glucose Test', 'Fusce consequat.', '13.5 - 17.5 g/dL', 370.26, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (26, 'Glucose Test', 'Pellentesque viverra pede ac diam.', '70 - 100 mg/dL', 499.04, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (27, 'Vitamin D Test', 'Duis consequat dui nec nisi volutpat eleifend.', '0.5 - 1.2', 383.13, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (28, 'Complete Blood Count', 'Etiam vel augue.', 'Normal', 354.4, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (29, 'Lipid Panel', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '3.5 - 5.0', 786.65, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (30, 'Glucose Test', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '13.5 - 17.5 g/dL', 775.06, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (31, 'Thyroid Function', 'Mauris sit amet eros.', '3.5 - 5.0', 599.14, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (32, 'Lipid Panel', 'Vestibulum sed magna at nunc commodo placerat.', '13.5 - 17.5 g/dL', 94.07, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (33, 'Lipid Panel', 'Ut tellus.', '13.5 - 17.5 g/dL', 872.74, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (34, 'Kidney Function Test', 'Praesent blandit.', '13.5 - 17.5 g/dL', 766.43, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (35, 'Hemoglobin A1c', 'Cras in purus eu magna vulputate luctus.', 'Normal', 872.98, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (36, 'Urinalysis', 'In congue.', '70 - 100 mg/dL', 326.29, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (37, 'Kidney Function Test', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '70 - 100 mg/dL', 365.2, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (38, 'Lipid Panel', 'Integer tincidunt ante vel ipsum.', '13.5 - 17.5 g/dL', 570.45, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (39, 'Hemoglobin A1c', 'Morbi a ipsum.', '70 - 100 mg/dL', 861.19, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (40, 'Glucose Test', 'Nam dui.', 'Normal', 50.76, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (41, 'Hemoglobin A1c', 'Morbi ut odio.', '70 - 100 mg/dL', 921.47, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (42, 'Thyroid Function', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '3.5 - 5.0', 639.02, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (43, 'Thyroid Function', 'Suspendisse ornare consequat lectus.', '13.5 - 17.5 g/dL', 175.42, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (44, 'Lipid Panel', 'Quisque porta volutpat erat.', '13.5 - 17.5 g/dL', 257.19, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (45, 'Liver Function Test', 'Morbi vel lectus in quam fringilla rhoncus.', '70 - 100 mg/dL', 974.41, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (46, 'Liver Function Test', 'Nulla ac enim.', 'Normal', 430.21, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (47, 'Glucose Test', 'Nullam varius.', '3.5 - 5.0', 852.92, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (48, 'Vitamin D Test', 'Sed ante.', '70 - 100 mg/dL', 941.73, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (49, 'Urinalysis', 'Cras in purus eu magna vulputate luctus.', '0.5 - 1.2', 363.42, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (50, 'Electrolyte Panel', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '3.5 - 5.0', 757.4, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (51, 'Hemoglobin A1c', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '70 - 100 mg/dL', 377.69, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (52, 'Glucose Test', 'Aliquam erat volutpat.', '3.5 - 5.0', 166.01, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (53, 'Thyroid Function', 'Pellentesque at nulla.', '3.5 - 5.0', 347.14, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (54, 'Complete Blood Count', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '0.5 - 1.2', 373.25, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (55, 'Complete Blood Count', 'Integer a nibh.', 'Normal', 663.19, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (56, 'Lipid Panel', 'Morbi non lectus.', '3.5 - 5.0', 296.04, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (57, 'Vitamin D Test', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '3.5 - 5.0', 414.79, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (58, 'Liver Function Test', 'Curabitur in libero ut massa volutpat convallis.', '0.5 - 1.2', 156.56, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (59, 'Liver Function Test', 'Nam tristique tortor eu pede.', 'Negative', 836.18, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (60, 'Glucose Test', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Normal', 721.3, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (61, 'Glucose Test', 'Suspendisse potenti.', '13.5 - 17.5 g/dL', 270.74, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (62, 'Electrolyte Panel', 'Nunc nisl.', '3.5 - 5.0', 120.51, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (63, 'Glucose Test', 'Praesent blandit lacinia erat.', '13.5 - 17.5 g/dL', 697.66, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (64, 'Urinalysis', 'Aliquam quis turpis eget elit sodales scelerisque.', 'Negative', 929.63, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (65, 'Complete Blood Count', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '3.5 - 5.0', 837.96, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (66, 'Electrolyte Panel', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '0.5 - 1.2', 426.66, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (67, 'Lipid Panel', 'Nulla suscipit ligula in lacus.', '70 - 100 mg/dL', 879.63, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (68, 'Vitamin D Test', 'Nulla suscipit ligula in lacus.', 'Normal', 878.58, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (69, 'Vitamin D Test', 'Integer ac neque.', '70 - 100 mg/dL', 645.54, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (70, 'Complete Blood Count', 'Suspendisse potenti.', '13.5 - 17.5 g/dL', 432.71, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (71, 'Lipid Panel', 'Suspendisse potenti.', '3.5 - 5.0', 385.03, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (72, 'Electrolyte Panel', 'Maecenas tincidunt lacus at velit.', 'Normal', 599.79, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (73, 'Electrolyte Panel', 'Aenean lectus.', '13.5 - 17.5 g/dL', 936.61, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (74, 'Kidney Function Test', 'Praesent id massa id nisl venenatis lacinia.', '13.5 - 17.5 g/dL', 931.75, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (75, 'Thyroid Function', 'Suspendisse ornare consequat lectus.', '70 - 100 mg/dL', 931.1, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (76, 'Hemoglobin A1c', 'Duis mattis egestas metus.', 'Negative', 624.05, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (77, 'Hemoglobin A1c', 'Morbi ut odio.', '70 - 100 mg/dL', 938.04, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (78, 'Urinalysis', 'Maecenas ut massa quis augue luctus tincidunt.', '0.5 - 1.2', 887.03, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (79, 'Glucose Test', 'Curabitur gravida nisi at nibh.', '13.5 - 17.5 g/dL', 421.6, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (80, 'Thyroid Function', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '3.5 - 5.0', 776.33, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (81, 'Urinalysis', 'Curabitur in libero ut massa volutpat convallis.', 'Normal', 129.95, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (82, 'Lipid Panel', 'Curabitur at ipsum ac tellus semper interdum.', '13.5 - 17.5 g/dL', 654.71, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (83, 'Electrolyte Panel', 'Suspendisse potenti.', 'Normal', 310.47, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (84, 'Urinalysis', 'Praesent lectus.', 'Negative', 896.67, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (85, 'Complete Blood Count', 'Praesent lectus.', '70 - 100 mg/dL', 342.0, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (86, 'Glucose Test', 'Morbi a ipsum.', '0.5 - 1.2', 259.19, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (87, 'Liver Function Test', 'Vivamus in felis eu sapien cursus vestibulum.', '3.5 - 5.0', 886.24, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (88, 'Liver Function Test', 'In hac habitasse platea dictumst.', '3.5 - 5.0', 921.25, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (89, 'Complete Blood Count', 'Maecenas rhoncus aliquam lacus.', 'Normal', 435.7, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (90, 'Lipid Panel', 'Morbi a ipsum.', '0.5 - 1.2', 587.7, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (91, 'Liver Function Test', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '3.5 - 5.0', 229.2, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (92, 'Complete Blood Count', 'Nullam porttitor lacus at turpis.', 'Normal', 218.62, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (93, 'Urinalysis', 'Donec ut mauris eget massa tempor convallis.', '3.5 - 5.0', 781.99, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (94, 'Vitamin D Test', 'Nulla ac enim.', 'Normal', 995.11, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (95, 'Glucose Test', 'Proin interdum mauris non ligula pellentesque ultrices.', 'Normal', 464.97, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (96, 'Electrolyte Panel', 'Vestibulum ac est lacinia nisi venenatis tristique.', 'Negative', 442.41, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (97, 'Glucose Test', 'Nulla facilisi.', '70 - 100 mg/dL', 96.8, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (98, 'Thyroid Function', 'Mauris lacinia sapien quis libero.', 'Normal', 270.2, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (99, 'Electrolyte Panel', 'Aliquam sit amet diam in magna bibendum imperdiet.', '0.5 - 1.2', 510.26, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (100, 'Lipid Panel', 'Aliquam erat volutpat.', '0.5 - 1.2', 118.55, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (101, 'Glucose Test', 'Proin at turpis a pede posuere nonummy.', 'Normal', 196.24, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (102, 'Electrolyte Panel', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '70 - 100 mg/dL', 805.13, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (103, 'Complete Blood Count', 'Nulla mollis molestie lorem.', '0.5 - 1.2', 311.31, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (104, 'Urinalysis', 'Integer ac neque.', '70 - 100 mg/dL', 726.25, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (105, 'Urinalysis', 'Aliquam sit amet diam in magna bibendum imperdiet.', '0.5 - 1.2', 471.78, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (106, 'Hemoglobin A1c', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '13.5 - 17.5 g/dL', 971.95, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (107, 'Electrolyte Panel', 'Nam dui.', '0.5 - 1.2', 591.55, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (108, 'Urinalysis', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '70 - 100 mg/dL', 277.47, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (109, 'Glucose Test', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '70 - 100 mg/dL', 362.65, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (110, 'Lipid Panel', 'Donec vitae nisi.', '13.5 - 17.5 g/dL', 321.03, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (111, 'Kidney Function Test', 'Curabitur gravida nisi at nibh.', 'Negative', 583.05, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (112, 'Hemoglobin A1c', 'Morbi non quam nec dui luctus rutrum.', '70 - 100 mg/dL', 210.49, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (113, 'Kidney Function Test', 'Nulla ut erat id mauris vulputate elementum.', '13.5 - 17.5 g/dL', 487.19, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (114, 'Electrolyte Panel', 'Pellentesque eget nunc.', '0.5 - 1.2', 79.6, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (115, 'Glucose Test', 'Nulla tellus.', '0.5 - 1.2', 572.12, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (116, 'Thyroid Function', 'Nullam porttitor lacus at turpis.', '0.5 - 1.2', 187.37, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (117, 'Urinalysis', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '13.5 - 17.5 g/dL', 398.43, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (118, 'Lipid Panel', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '0.5 - 1.2', 97.95, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (119, 'Vitamin D Test', 'Fusce consequat.', '3.5 - 5.0', 532.51, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (120, 'Vitamin D Test', 'Cras pellentesque volutpat dui.', 'Negative', 854.38, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (121, 'Vitamin D Test', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Negative', 663.77, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (122, 'Complete Blood Count', 'Curabitur gravida nisi at nibh.', 'Negative', 234.17, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (123, 'Complete Blood Count', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'Negative', 957.41, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (124, 'Complete Blood Count', 'Mauris ullamcorper purus sit amet nulla.', '13.5 - 17.5 g/dL', 692.16, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (125, 'Kidney Function Test', 'In blandit ultrices enim.', 'Negative', 471.75, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (126, 'Thyroid Function', 'Donec posuere metus vitae ipsum.', '13.5 - 17.5 g/dL', 596.71, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (127, 'Urinalysis', 'Suspendisse potenti.', '70 - 100 mg/dL', 362.72, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (128, 'Glucose Test', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Normal', 603.07, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (129, 'Hemoglobin A1c', 'Vestibulum ac est lacinia nisi venenatis tristique.', '70 - 100 mg/dL', 157.62, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (130, 'Thyroid Function', 'Morbi vel lectus in quam fringilla rhoncus.', '70 - 100 mg/dL', 822.63, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (131, 'Electrolyte Panel', 'Vestibulum sed magna at nunc commodo placerat.', 'Negative', 863.54, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (132, 'Complete Blood Count', 'Donec posuere metus vitae ipsum.', '13.5 - 17.5 g/dL', 377.02, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (133, 'Kidney Function Test', 'Duis mattis egestas metus.', '0.5 - 1.2', 778.44, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (134, 'Thyroid Function', 'In hac habitasse platea dictumst.', 'Normal', 488.28, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (135, 'Lipid Panel', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Negative', 758.17, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (136, 'Urinalysis', 'Vivamus vestibulum sagittis sapien.', 'Negative', 338.25, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (137, 'Urinalysis', 'Donec semper sapien a libero.', '13.5 - 17.5 g/dL', 629.59, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (138, 'Thyroid Function', 'Sed accumsan felis.', '70 - 100 mg/dL', 494.81, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (139, 'Lipid Panel', 'Nullam sit amet turpis elementum ligula vehicula consequat.', '70 - 100 mg/dL', 709.67, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (140, 'Electrolyte Panel', 'Donec dapibus.', 'Normal', 300.15, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (141, 'Urinalysis', 'Nulla tellus.', '0.5 - 1.2', 98.0, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (142, 'Glucose Test', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '3.5 - 5.0', 461.01, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (143, 'Glucose Test', 'Vestibulum ac est lacinia nisi venenatis tristique.', '13.5 - 17.5 g/dL', 834.82, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (144, 'Urinalysis', 'In blandit ultrices enim.', '70 - 100 mg/dL', 725.08, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (145, 'Vitamin D Test', 'Etiam justo.', '3.5 - 5.0', 958.07, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (146, 'Glucose Test', 'In congue.', '13.5 - 17.5 g/dL', 462.74, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (147, 'Urinalysis', 'Morbi ut odio.', '70 - 100 mg/dL', 939.44, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (148, 'Lipid Panel', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '13.5 - 17.5 g/dL', 668.45, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (149, 'Thyroid Function', 'Quisque porta volutpat erat.', '70 - 100 mg/dL', 93.78, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (150, 'Vitamin D Test', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Negative', 169.27, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (151, 'Urinalysis', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '70 - 100 mg/dL', 859.41, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (152, 'Glucose Test', 'Etiam pretium iaculis justo.', 'Negative', 445.72, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (153, 'Kidney Function Test', 'Nam tristique tortor eu pede.', 'Negative', 489.2, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (154, 'Lipid Panel', 'Suspendisse potenti.', '3.5 - 5.0', 365.3, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (155, 'Electrolyte Panel', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '3.5 - 5.0', 283.82, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (156, 'Electrolyte Panel', 'Duis aliquam convallis nunc.', '0.5 - 1.2', 737.64, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (157, 'Liver Function Test', 'Donec dapibus.', 'Normal', 762.24, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (158, 'Vitamin D Test', 'Cras in purus eu magna vulputate luctus.', '3.5 - 5.0', 536.64, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (159, 'Hemoglobin A1c', 'In hac habitasse platea dictumst.', 'Negative', 937.48, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (160, 'Lipid Panel', 'Pellentesque viverra pede ac diam.', '13.5 - 17.5 g/dL', 555.18, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (161, 'Thyroid Function', 'Nullam molestie nibh in lectus.', '0.5 - 1.2', 734.8, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (162, 'Urinalysis', 'In quis justo.', 'Negative', 702.07, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (163, 'Thyroid Function', 'Etiam pretium iaculis justo.', '0.5 - 1.2', 974.95, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (164, 'Lipid Panel', 'Etiam justo.', 'Negative', 284.76, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (165, 'Liver Function Test', 'Pellentesque viverra pede ac diam.', '70 - 100 mg/dL', 703.91, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (166, 'Liver Function Test', 'Proin eu mi.', 'Negative', 848.44, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (167, 'Electrolyte Panel', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '3.5 - 5.0', 281.8, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (168, 'Hemoglobin A1c', 'Duis at velit eu est congue elementum.', 'Normal', 516.29, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (169, 'Electrolyte Panel', 'Morbi a ipsum.', '13.5 - 17.5 g/dL', 235.67, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (170, 'Vitamin D Test', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '3.5 - 5.0', 330.31, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (171, 'Glucose Test', 'Duis aliquam convallis nunc.', '70 - 100 mg/dL', 151.3, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (172, 'Thyroid Function', 'Duis bibendum.', 'Normal', 205.61, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (173, 'Lipid Panel', 'Phasellus in felis.', '0.5 - 1.2', 602.91, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (174, 'Urinalysis', 'Etiam faucibus cursus urna.', 'Negative', 442.34, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (175, 'Liver Function Test', 'In quis justo.', '13.5 - 17.5 g/dL', 798.88, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (176, 'Lipid Panel', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '3.5 - 5.0', 50.21, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (177, 'Liver Function Test', 'Vivamus vel nulla eget eros elementum pellentesque.', '13.5 - 17.5 g/dL', 259.16, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (178, 'Complete Blood Count', 'Nulla facilisi.', 'Negative', 821.57, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (179, 'Urinalysis', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Negative', 692.89, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (180, 'Complete Blood Count', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '0.5 - 1.2', 269.01, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (181, 'Kidney Function Test', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '3.5 - 5.0', 788.59, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (182, 'Electrolyte Panel', 'Fusce posuere felis sed lacus.', '3.5 - 5.0', 249.64, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (183, 'Complete Blood Count', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '3.5 - 5.0', 391.24, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (184, 'Urinalysis', 'In quis justo.', 'Normal', 510.12, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (185, 'Glucose Test', 'Curabitur in libero ut massa volutpat convallis.', '0.5 - 1.2', 916.24, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (186, 'Vitamin D Test', 'Mauris sit amet eros.', 'Normal', 704.3, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (187, 'Hemoglobin A1c', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '3.5 - 5.0', 903.33, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (188, 'Complete Blood Count', 'Suspendisse ornare consequat lectus.', '3.5 - 5.0', 818.13, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (189, 'Glucose Test', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Negative', 579.91, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (190, 'Liver Function Test', 'Duis aliquam convallis nunc.', '0.5 - 1.2', 174.38, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (191, 'Liver Function Test', 'In sagittis dui vel nisl.', '3.5 - 5.0', 594.57, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (192, 'Hemoglobin A1c', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Negative', 377.29, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (193, 'Urinalysis', 'In hac habitasse platea dictumst.', '3.5 - 5.0', 810.74, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (194, 'Liver Function Test', 'Nullam molestie nibh in lectus.', 'Negative', 626.2, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (195, 'Liver Function Test', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '3.5 - 5.0', 205.83, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (196, 'Thyroid Function', 'Ut tellus.', '13.5 - 17.5 g/dL', 382.02, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (197, 'Glucose Test', 'Nulla nisl.', '0.5 - 1.2', 111.53, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (198, 'Complete Blood Count', 'In congue.', '0.5 - 1.2', 771.22, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (199, 'Urinalysis', 'Cras in purus eu magna vulputate luctus.', 'Normal', 404.23, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (200, 'Glucose Test', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '13.5 - 17.5 g/dL', 131.99, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (201, 'Urinalysis', 'Integer ac neque.', 'Negative', 885.04, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (202, 'Hemoglobin A1c', 'Nam dui.', '13.5 - 17.5 g/dL', 771.57, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (203, 'Urinalysis', 'Nullam porttitor lacus at turpis.', '3.5 - 5.0', 832.12, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (204, 'Urinalysis', 'Cras pellentesque volutpat dui.', '70 - 100 mg/dL', 541.1, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (205, 'Electrolyte Panel', 'Aenean sit amet justo.', 'Normal', 465.53, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (206, 'Vitamin D Test', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'Negative', 76.91, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (207, 'Urinalysis', 'Integer tincidunt ante vel ipsum.', '70 - 100 mg/dL', 189.53, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (208, 'Electrolyte Panel', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Normal', 118.07, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (209, 'Kidney Function Test', 'Nulla nisl.', '0.5 - 1.2', 666.41, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (210, 'Liver Function Test', 'Duis at velit eu est congue elementum.', 'Normal', 417.33, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (211, 'Hemoglobin A1c', 'Pellentesque viverra pede ac diam.', '70 - 100 mg/dL', 138.05, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (212, 'Urinalysis', 'Phasellus id sapien in sapien iaculis congue.', '70 - 100 mg/dL', 196.11, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (213, 'Hemoglobin A1c', 'Vivamus tortor.', '0.5 - 1.2', 374.22, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (214, 'Liver Function Test', 'Integer non velit.', '0.5 - 1.2', 675.02, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (215, 'Vitamin D Test', 'Donec dapibus.', 'Normal', 316.02, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (216, 'Glucose Test', 'Vestibulum sed magna at nunc commodo placerat.', 'Normal', 78.79, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (217, 'Hemoglobin A1c', 'Proin eu mi.', '70 - 100 mg/dL', 465.2, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (218, 'Thyroid Function', 'Aenean fermentum.', 'Normal', 641.98, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (219, 'Lipid Panel', 'Sed vel enim sit amet nunc viverra dapibus.', '13.5 - 17.5 g/dL', 426.98, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (220, 'Urinalysis', 'Curabitur in libero ut massa volutpat convallis.', '70 - 100 mg/dL', 63.12, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (221, 'Liver Function Test', 'Pellentesque viverra pede ac diam.', '70 - 100 mg/dL', 516.92, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (222, 'Electrolyte Panel', 'Mauris sit amet eros.', 'Negative', 661.09, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (223, 'Complete Blood Count', 'Maecenas tincidunt lacus at velit.', '13.5 - 17.5 g/dL', 631.6, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (224, 'Thyroid Function', 'Donec ut dolor.', '3.5 - 5.0', 817.5, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (225, 'Thyroid Function', 'Aenean lectus.', '3.5 - 5.0', 660.01, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (226, 'Kidney Function Test', 'Phasellus sit amet erat.', '3.5 - 5.0', 800.29, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (227, 'Thyroid Function', 'Etiam justo.', '0.5 - 1.2', 143.48, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (228, 'Glucose Test', 'Sed sagittis.', '13.5 - 17.5 g/dL', 175.79, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (229, 'Complete Blood Count', 'Nam dui.', '13.5 - 17.5 g/dL', 438.74, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (230, 'Kidney Function Test', 'Praesent lectus.', '13.5 - 17.5 g/dL', 724.16, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (231, 'Liver Function Test', 'Duis aliquam convallis nunc.', 'Normal', 115.89, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (232, 'Glucose Test', 'In eleifend quam a odio.', '0.5 - 1.2', 950.95, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (233, 'Hemoglobin A1c', 'Proin eu mi.', '3.5 - 5.0', 638.42, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (234, 'Electrolyte Panel', 'Fusce consequat.', '0.5 - 1.2', 639.42, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (235, 'Electrolyte Panel', 'Mauris ullamcorper purus sit amet nulla.', 'Negative', 583.5, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (236, 'Hemoglobin A1c', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '13.5 - 17.5 g/dL', 737.87, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (237, 'Electrolyte Panel', 'Pellentesque at nulla.', 'Normal', 738.25, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (238, 'Glucose Test', 'Morbi non lectus.', 'Negative', 712.02, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (239, 'Glucose Test', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Normal', 335.97, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (240, 'Electrolyte Panel', 'Vivamus tortor.', '13.5 - 17.5 g/dL', 160.23, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (241, 'Vitamin D Test', 'Cras in purus eu magna vulputate luctus.', '3.5 - 5.0', 397.72, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (242, 'Complete Blood Count', 'Etiam vel augue.', 'Negative', 398.32, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (243, 'Liver Function Test', 'Nulla nisl.', '13.5 - 17.5 g/dL', 603.41, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (244, 'Complete Blood Count', 'Curabitur convallis.', 'Negative', 228.48, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (245, 'Lipid Panel', 'Aenean fermentum.', '3.5 - 5.0', 364.85, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (246, 'Complete Blood Count', 'Quisque id justo sit amet sapien dignissim vestibulum.', '70 - 100 mg/dL', 74.96, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (247, 'Lipid Panel', 'Proin eu mi.', '3.5 - 5.0', 564.17, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (248, 'Kidney Function Test', 'Duis at velit eu est congue elementum.', 'Normal', 772.89, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (249, 'Glucose Test', 'Sed sagittis.', '0.5 - 1.2', 91.39, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (250, 'Complete Blood Count', 'Morbi ut odio.', 'Normal', 597.48, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (251, 'Complete Blood Count', 'Etiam vel augue.', '13.5 - 17.5 g/dL', 877.93, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (252, 'Glucose Test', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '13.5 - 17.5 g/dL', 677.24, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (253, 'Vitamin D Test', 'Aenean auctor gravida sem.', '70 - 100 mg/dL', 224.79, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (254, 'Lipid Panel', 'Aliquam sit amet diam in magna bibendum imperdiet.', '0.5 - 1.2', 620.4, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (255, 'Complete Blood Count', 'Donec quis orci eget orci vehicula condimentum.', '13.5 - 17.5 g/dL', 152.53, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (256, 'Electrolyte Panel', 'Nulla ac enim.', 'Normal', 169.13, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (257, 'Complete Blood Count', 'Pellentesque at nulla.', '0.5 - 1.2', 453.04, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (258, 'Electrolyte Panel', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Negative', 143.95, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (259, 'Glucose Test', 'Phasellus id sapien in sapien iaculis congue.', 'Normal', 820.05, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (260, 'Hemoglobin A1c', 'Fusce posuere felis sed lacus.', '13.5 - 17.5 g/dL', 706.71, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (261, 'Complete Blood Count', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '0.5 - 1.2', 620.54, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (262, 'Glucose Test', 'Curabitur gravida nisi at nibh.', 'Normal', 93.96, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (263, 'Lipid Panel', 'Donec quis orci eget orci vehicula condimentum.', '3.5 - 5.0', 955.25, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (264, 'Lipid Panel', 'Vestibulum sed magna at nunc commodo placerat.', '3.5 - 5.0', 503.52, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (265, 'Urinalysis', 'Integer ac leo.', '0.5 - 1.2', 665.06, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (266, 'Thyroid Function', 'Duis consequat dui nec nisi volutpat eleifend.', '70 - 100 mg/dL', 724.66, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (267, 'Lipid Panel', 'Duis aliquam convallis nunc.', '13.5 - 17.5 g/dL', 374.96, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (268, 'Liver Function Test', 'Aliquam quis turpis eget elit sodales scelerisque.', '0.5 - 1.2', 919.24, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (269, 'Hemoglobin A1c', 'Curabitur in libero ut massa volutpat convallis.', '3.5 - 5.0', 933.5, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (270, 'Lipid Panel', 'Morbi quis tortor id nulla ultrices aliquet.', '3.5 - 5.0', 482.49, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (271, 'Glucose Test', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Normal', 624.25, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (272, 'Urinalysis', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '3.5 - 5.0', 182.58, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (273, 'Vitamin D Test', 'Suspendisse potenti.', '13.5 - 17.5 g/dL', 933.3, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (274, 'Hemoglobin A1c', 'Quisque ut erat.', '3.5 - 5.0', 828.34, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (275, 'Vitamin D Test', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '13.5 - 17.5 g/dL', 440.96, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (276, 'Liver Function Test', 'In congue.', '13.5 - 17.5 g/dL', 771.88, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (277, 'Liver Function Test', 'Nunc rhoncus dui vel sem.', 'Negative', 816.15, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (278, 'Thyroid Function', 'Nam tristique tortor eu pede.', '13.5 - 17.5 g/dL', 804.94, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (279, 'Electrolyte Panel', 'Sed accumsan felis.', '3.5 - 5.0', 236.84, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (280, 'Vitamin D Test', 'Aenean sit amet justo.', '3.5 - 5.0', 831.64, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (281, 'Thyroid Function', 'Duis ac nibh.', '3.5 - 5.0', 138.29, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (282, 'Glucose Test', 'Duis aliquam convallis nunc.', '3.5 - 5.0', 366.36, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (283, 'Electrolyte Panel', 'In hac habitasse platea dictumst.', '13.5 - 17.5 g/dL', 765.79, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (284, 'Vitamin D Test', 'Mauris ullamcorper purus sit amet nulla.', '0.5 - 1.2', 299.62, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (285, 'Urinalysis', 'Sed sagittis.', '13.5 - 17.5 g/dL', 172.56, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (286, 'Vitamin D Test', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '13.5 - 17.5 g/dL', 68.45, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (287, 'Thyroid Function', 'Integer non velit.', '0.5 - 1.2', 464.56, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (288, 'Complete Blood Count', 'Duis consequat dui nec nisi volutpat eleifend.', 'Negative', 424.77, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (289, 'Urinalysis', 'Duis at velit eu est congue elementum.', '70 - 100 mg/dL', 332.84, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (290, 'Glucose Test', 'In hac habitasse platea dictumst.', 'Negative', 764.36, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (291, 'Kidney Function Test', 'Cras non velit nec nisi vulputate nonummy.', '70 - 100 mg/dL', 772.13, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (292, 'Thyroid Function', 'Aliquam erat volutpat.', '13.5 - 17.5 g/dL', 173.55, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (293, 'Complete Blood Count', 'Nulla ac enim.', '0.5 - 1.2', 290.23, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (294, 'Electrolyte Panel', 'Duis ac nibh.', 'Normal', 534.79, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (295, 'Hemoglobin A1c', 'Donec posuere metus vitae ipsum.', 'Negative', 350.19, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (296, 'Urinalysis', 'Nullam varius.', '13.5 - 17.5 g/dL', 298.2, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (297, 'Electrolyte Panel', 'Integer ac leo.', '70 - 100 mg/dL', 950.59, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (298, 'Hemoglobin A1c', 'Aenean fermentum.', 'Normal', 563.32, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (299, 'Complete Blood Count', 'Quisque id justo sit amet sapien dignissim vestibulum.', 'Normal', 431.75, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (300, 'Kidney Function Test', 'Suspendisse accumsan tortor quis turpis.', '3.5 - 5.0', 307.47, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (301, 'Hemoglobin A1c', 'Praesent id massa id nisl venenatis lacinia.', '0.5 - 1.2', 85.42, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (302, 'Kidney Function Test', 'Morbi a ipsum.', '3.5 - 5.0', 877.64, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (303, 'Vitamin D Test', 'Proin at turpis a pede posuere nonummy.', 'Normal', 652.79, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (304, 'Kidney Function Test', 'Quisque ut erat.', '13.5 - 17.5 g/dL', 619.03, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (305, 'Glucose Test', 'Maecenas tincidunt lacus at velit.', '13.5 - 17.5 g/dL', 604.0, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (306, 'Kidney Function Test', 'Proin eu mi.', '70 - 100 mg/dL', 401.1, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (307, 'Glucose Test', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Negative', 943.61, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (308, 'Vitamin D Test', 'Donec vitae nisi.', '13.5 - 17.5 g/dL', 355.02, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (309, 'Electrolyte Panel', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Negative', 237.28, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (310, 'Hemoglobin A1c', 'Duis mattis egestas metus.', 'Normal', 453.68, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (311, 'Lipid Panel', 'Pellentesque ultrices mattis odio.', 'Negative', 671.71, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (312, 'Complete Blood Count', 'Vivamus vel nulla eget eros elementum pellentesque.', '3.5 - 5.0', 884.46, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (313, 'Complete Blood Count', 'Nam dui.', 'Normal', 782.51, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (314, 'Thyroid Function', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Negative', 707.17, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (315, 'Vitamin D Test', 'Vestibulum sed magna at nunc commodo placerat.', 'Normal', 121.78, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (316, 'Electrolyte Panel', 'Curabitur convallis.', '0.5 - 1.2', 404.36, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (317, 'Electrolyte Panel', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '13.5 - 17.5 g/dL', 497.49, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (318, 'Lipid Panel', 'Morbi porttitor lorem id ligula.', 'Normal', 431.44, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (319, 'Electrolyte Panel', 'Curabitur in libero ut massa volutpat convallis.', '3.5 - 5.0', 65.5, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (320, 'Kidney Function Test', 'Aenean auctor gravida sem.', '13.5 - 17.5 g/dL', 186.17, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (321, 'Hemoglobin A1c', 'Vestibulum ac est lacinia nisi venenatis tristique.', '13.5 - 17.5 g/dL', 314.08, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (322, 'Lipid Panel', 'Duis aliquam convallis nunc.', '0.5 - 1.2', 172.32, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (323, 'Complete Blood Count', 'Maecenas pulvinar lobortis est.', 'Negative', 445.32, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (324, 'Liver Function Test', 'Pellentesque eget nunc.', '3.5 - 5.0', 457.67, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (325, 'Thyroid Function', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Negative', 732.47, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (326, 'Electrolyte Panel', 'Etiam pretium iaculis justo.', '70 - 100 mg/dL', 559.06, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (327, 'Complete Blood Count', 'Pellentesque viverra pede ac diam.', '0.5 - 1.2', 293.31, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (328, 'Urinalysis', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '0.5 - 1.2', 680.76, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (329, 'Kidney Function Test', 'Morbi non quam nec dui luctus rutrum.', '0.5 - 1.2', 485.25, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (330, 'Vitamin D Test', 'Nulla suscipit ligula in lacus.', '3.5 - 5.0', 714.38, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (331, 'Liver Function Test', 'Etiam vel augue.', 'Negative', 745.65, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (332, 'Electrolyte Panel', 'Phasellus sit amet erat.', '13.5 - 17.5 g/dL', 210.56, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (333, 'Complete Blood Count', 'Morbi a ipsum.', 'Normal', 309.53, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (334, 'Electrolyte Panel', 'In hac habitasse platea dictumst.', 'Negative', 506.06, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (335, 'Glucose Test', 'Vestibulum ac est lacinia nisi venenatis tristique.', 'Normal', 700.57, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (336, 'Glucose Test', 'Mauris sit amet eros.', 'Normal', 194.22, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (337, 'Glucose Test', 'Nulla justo.', '13.5 - 17.5 g/dL', 770.28, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (338, 'Hemoglobin A1c', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '0.5 - 1.2', 576.56, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (339, 'Glucose Test', 'Nulla mollis molestie lorem.', '13.5 - 17.5 g/dL', 730.49, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (340, 'Vitamin D Test', 'Phasellus sit amet erat.', '13.5 - 17.5 g/dL', 777.89, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (341, 'Hemoglobin A1c', 'Suspendisse potenti.', '3.5 - 5.0', 515.59, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (342, 'Lipid Panel', 'Quisque id justo sit amet sapien dignissim vestibulum.', '13.5 - 17.5 g/dL', 396.98, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (343, 'Kidney Function Test', 'Maecenas tincidunt lacus at velit.', 'Normal', 267.12, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (344, 'Liver Function Test', 'Morbi quis tortor id nulla ultrices aliquet.', '3.5 - 5.0', 361.84, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (345, 'Thyroid Function', 'Quisque id justo sit amet sapien dignissim vestibulum.', '13.5 - 17.5 g/dL', 323.4, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (346, 'Lipid Panel', 'Proin eu mi.', 'Normal', 580.25, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (347, 'Liver Function Test', 'In hac habitasse platea dictumst.', '0.5 - 1.2', 668.85, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (348, 'Complete Blood Count', 'Cras in purus eu magna vulputate luctus.', 'Normal', 751.68, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (349, 'Complete Blood Count', 'In hac habitasse platea dictumst.', 'Negative', 162.02, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (350, 'Glucose Test', 'Praesent id massa id nisl venenatis lacinia.', '70 - 100 mg/dL', 675.4, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (351, 'Kidney Function Test', 'Nunc nisl.', 'Negative', 609.45, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (352, 'Glucose Test', 'Ut tellus.', 'Negative', 319.87, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (353, 'Vitamin D Test', 'Morbi quis tortor id nulla ultrices aliquet.', '0.5 - 1.2', 978.14, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (354, 'Glucose Test', 'Duis consequat dui nec nisi volutpat eleifend.', '13.5 - 17.5 g/dL', 68.67, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (355, 'Vitamin D Test', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '0.5 - 1.2', 528.84, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (356, 'Hemoglobin A1c', 'In hac habitasse platea dictumst.', 'Normal', 650.17, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (357, 'Electrolyte Panel', 'Aenean auctor gravida sem.', '13.5 - 17.5 g/dL', 600.58, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (358, 'Hemoglobin A1c', 'Duis ac nibh.', '70 - 100 mg/dL', 929.36, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (359, 'Lipid Panel', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '13.5 - 17.5 g/dL', 915.75, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (360, 'Lipid Panel', 'Nulla nisl.', '13.5 - 17.5 g/dL', 457.4, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (361, 'Thyroid Function', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '13.5 - 17.5 g/dL', 776.84, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (362, 'Lipid Panel', 'Etiam vel augue.', '13.5 - 17.5 g/dL', 126.0, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (363, 'Glucose Test', 'Nulla mollis molestie lorem.', 'Normal', 304.01, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (364, 'Vitamin D Test', 'Phasellus id sapien in sapien iaculis congue.', 'Normal', 796.51, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (365, 'Glucose Test', 'Pellentesque ultrices mattis odio.', 'Normal', 744.2, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (366, 'Thyroid Function', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '0.5 - 1.2', 480.13, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (367, 'Lipid Panel', 'Nulla tellus.', '13.5 - 17.5 g/dL', 156.44, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (368, 'Urinalysis', 'Etiam faucibus cursus urna.', '3.5 - 5.0', 479.93, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (369, 'Electrolyte Panel', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '0.5 - 1.2', 870.31, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (370, 'Urinalysis', 'Pellentesque at nulla.', '0.5 - 1.2', 761.51, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (371, 'Hemoglobin A1c', 'Suspendisse ornare consequat lectus.', 'Normal', 569.83, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (372, 'Thyroid Function', 'Phasellus sit amet erat.', '0.5 - 1.2', 865.71, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (373, 'Lipid Panel', 'Sed accumsan felis.', 'Normal', 819.84, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (374, 'Thyroid Function', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '0.5 - 1.2', 395.85, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (375, 'Vitamin D Test', 'Nullam varius.', '13.5 - 17.5 g/dL', 89.81, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (376, 'Thyroid Function', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '0.5 - 1.2', 615.52, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (377, 'Lipid Panel', 'Vivamus vestibulum sagittis sapien.', '3.5 - 5.0', 369.67, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (378, 'Vitamin D Test', 'Morbi quis tortor id nulla ultrices aliquet.', 'Negative', 998.42, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (379, 'Electrolyte Panel', 'Proin eu mi.', 'Negative', 696.07, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (380, 'Electrolyte Panel', 'Aliquam erat volutpat.', '3.5 - 5.0', 507.47, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (381, 'Hemoglobin A1c', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '0.5 - 1.2', 751.66, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (382, 'Thyroid Function', 'Maecenas pulvinar lobortis est.', 'Normal', 61.01, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (383, 'Lipid Panel', 'Etiam pretium iaculis justo.', '3.5 - 5.0', 548.42, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (384, 'Complete Blood Count', 'Donec dapibus.', '0.5 - 1.2', 755.92, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (385, 'Liver Function Test', 'Donec dapibus.', '3.5 - 5.0', 430.79, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (386, 'Urinalysis', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Normal', 268.23, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (387, 'Glucose Test', 'In congue.', '0.5 - 1.2', 382.82, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (388, 'Urinalysis', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '3.5 - 5.0', 256.4, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (389, 'Electrolyte Panel', 'Proin interdum mauris non ligula pellentesque ultrices.', '13.5 - 17.5 g/dL', 957.18, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (390, 'Vitamin D Test', 'Vivamus in felis eu sapien cursus vestibulum.', 'Negative', 925.77, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (391, 'Urinalysis', 'Maecenas ut massa quis augue luctus tincidunt.', '13.5 - 17.5 g/dL', 807.82, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (392, 'Glucose Test', 'Aliquam non mauris.', '13.5 - 17.5 g/dL', 335.53, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (393, 'Lipid Panel', 'Suspendisse potenti.', '13.5 - 17.5 g/dL', 448.16, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (394, 'Complete Blood Count', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '0.5 - 1.2', 810.63, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (395, 'Vitamin D Test', 'Pellentesque eget nunc.', '70 - 100 mg/dL', 223.65, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (396, 'Kidney Function Test', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '0.5 - 1.2', 821.67, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (397, 'Liver Function Test', 'Suspendisse ornare consequat lectus.', '0.5 - 1.2', 495.0, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (398, 'Urinalysis', 'Praesent blandit.', '3.5 - 5.0', 725.55, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (399, 'Thyroid Function', 'Integer a nibh.', 'Normal', 184.11, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (400, 'Liver Function Test', 'Phasellus in felis.', '3.5 - 5.0', 254.43, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (401, 'Glucose Test', 'Morbi non lectus.', '13.5 - 17.5 g/dL', 170.73, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (402, 'Complete Blood Count', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '3.5 - 5.0', 116.62, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (403, 'Lipid Panel', 'Vivamus in felis eu sapien cursus vestibulum.', '70 - 100 mg/dL', 582.51, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (404, 'Liver Function Test', 'Vivamus tortor.', 'Negative', 718.15, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (405, 'Thyroid Function', 'In congue.', '70 - 100 mg/dL', 118.18, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (406, 'Lipid Panel', 'Nulla tempus.', '70 - 100 mg/dL', 773.05, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (407, 'Hemoglobin A1c', 'Morbi non lectus.', '70 - 100 mg/dL', 974.36, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (408, 'Vitamin D Test', 'Nullam porttitor lacus at turpis.', 'Normal', 631.44, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (409, 'Kidney Function Test', 'In hac habitasse platea dictumst.', 'Negative', 870.62, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (410, 'Vitamin D Test', 'In congue.', 'Negative', 99.33, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (411, 'Thyroid Function', 'Aenean sit amet justo.', 'Negative', 408.5, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (412, 'Liver Function Test', 'Pellentesque ultrices mattis odio.', 'Normal', 638.7, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (413, 'Vitamin D Test', 'Nulla mollis molestie lorem.', 'Negative', 544.96, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (414, 'Thyroid Function', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '3.5 - 5.0', 960.7, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (415, 'Complete Blood Count', 'Nunc nisl.', 'Negative', 643.34, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (416, 'Urinalysis', 'Nullam porttitor lacus at turpis.', '0.5 - 1.2', 724.82, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (417, 'Complete Blood Count', 'Etiam faucibus cursus urna.', 'Negative', 791.94, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (418, 'Electrolyte Panel', 'Etiam faucibus cursus urna.', 'Normal', 54.73, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (419, 'Thyroid Function', 'Mauris lacinia sapien quis libero.', '3.5 - 5.0', 324.19, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (420, 'Hemoglobin A1c', 'Aliquam erat volutpat.', '0.5 - 1.2', 133.99, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (421, 'Glucose Test', 'Curabitur in libero ut massa volutpat convallis.', 'Negative', 122.6, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (422, 'Urinalysis', 'Donec dapibus.', '3.5 - 5.0', 347.11, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (423, 'Urinalysis', 'Aenean lectus.', '13.5 - 17.5 g/dL', 180.12, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (424, 'Glucose Test', 'Morbi non lectus.', '70 - 100 mg/dL', 455.19, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (425, 'Glucose Test', 'Donec quis orci eget orci vehicula condimentum.', 'Normal', 459.3, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (426, 'Urinalysis', 'In hac habitasse platea dictumst.', '3.5 - 5.0', 178.9, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (427, 'Urinalysis', 'Cras non velit nec nisi vulputate nonummy.', '13.5 - 17.5 g/dL', 314.89, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (428, 'Thyroid Function', 'Vivamus in felis eu sapien cursus vestibulum.', 'Normal', 358.21, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (429, 'Hemoglobin A1c', 'Mauris lacinia sapien quis libero.', '13.5 - 17.5 g/dL', 557.88, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (430, 'Lipid Panel', 'Nulla tellus.', '3.5 - 5.0', 63.08, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (431, 'Complete Blood Count', 'Morbi quis tortor id nulla ultrices aliquet.', 'Negative', 666.02, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (432, 'Hemoglobin A1c', 'In eleifend quam a odio.', '13.5 - 17.5 g/dL', 218.47, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (433, 'Lipid Panel', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '3.5 - 5.0', 772.06, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (434, 'Urinalysis', 'Sed vel enim sit amet nunc viverra dapibus.', 'Normal', 883.63, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (435, 'Glucose Test', 'Morbi a ipsum.', '0.5 - 1.2', 656.53, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (436, 'Kidney Function Test', 'Vivamus tortor.', '70 - 100 mg/dL', 593.95, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (437, 'Complete Blood Count', 'In eleifend quam a odio.', '3.5 - 5.0', 451.08, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (438, 'Urinalysis', 'Duis bibendum.', '13.5 - 17.5 g/dL', 653.11, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (439, 'Thyroid Function', 'Maecenas ut massa quis augue luctus tincidunt.', '70 - 100 mg/dL', 545.48, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (440, 'Electrolyte Panel', 'Pellentesque ultrices mattis odio.', 'Negative', 218.46, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (441, 'Glucose Test', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '0.5 - 1.2', 995.43, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (442, 'Thyroid Function', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '0.5 - 1.2', 461.32, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (443, 'Glucose Test', 'Morbi quis tortor id nulla ultrices aliquet.', 'Normal', 583.39, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (444, 'Glucose Test', 'Nulla tempus.', 'Negative', 931.3, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (445, 'Thyroid Function', 'Curabitur convallis.', '13.5 - 17.5 g/dL', 986.96, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (446, 'Hemoglobin A1c', 'In congue.', '70 - 100 mg/dL', 978.99, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (447, 'Thyroid Function', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '3.5 - 5.0', 862.68, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (448, 'Lipid Panel', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Negative', 110.23, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (449, 'Hemoglobin A1c', 'Sed vel enim sit amet nunc viverra dapibus.', 'Normal', 184.31, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (450, 'Thyroid Function', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '13.5 - 17.5 g/dL', 237.15, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (451, 'Lipid Panel', 'Vivamus tortor.', '3.5 - 5.0', 315.44, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (452, 'Kidney Function Test', 'Quisque porta volutpat erat.', '3.5 - 5.0', 889.21, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (453, 'Lipid Panel', 'Nulla mollis molestie lorem.', '13.5 - 17.5 g/dL', 787.37, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (454, 'Electrolyte Panel', 'Ut tellus.', '0.5 - 1.2', 616.68, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (455, 'Glucose Test', 'Nulla tellus.', 'Normal', 772.55, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (456, 'Lipid Panel', 'Proin risus.', 'Normal', 149.99, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (457, 'Vitamin D Test', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '3.5 - 5.0', 468.69, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (458, 'Lipid Panel', 'Praesent blandit.', 'Negative', 881.52, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (459, 'Complete Blood Count', 'Integer ac leo.', '13.5 - 17.5 g/dL', 465.24, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (460, 'Electrolyte Panel', 'Mauris sit amet eros.', '70 - 100 mg/dL', 623.5, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (461, 'Hemoglobin A1c', 'Etiam justo.', 'Normal', 251.78, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (462, 'Electrolyte Panel', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'Normal', 619.55, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (463, 'Lipid Panel', 'Vivamus in felis eu sapien cursus vestibulum.', 'Negative', 917.59, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (464, 'Hemoglobin A1c', 'In blandit ultrices enim.', '3.5 - 5.0', 487.14, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (465, 'Glucose Test', 'In hac habitasse platea dictumst.', '70 - 100 mg/dL', 881.96, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (466, 'Glucose Test', 'Quisque ut erat.', '13.5 - 17.5 g/dL', 120.55, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (467, 'Urinalysis', 'Nullam varius.', '3.5 - 5.0', 692.9, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (468, 'Electrolyte Panel', 'Donec ut dolor.', 'Normal', 460.26, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (469, 'Thyroid Function', 'Duis aliquam convallis nunc.', 'Normal', 775.36, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (470, 'Kidney Function Test', 'Vivamus vel nulla eget eros elementum pellentesque.', '0.5 - 1.2', 406.14, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (471, 'Electrolyte Panel', 'Fusce consequat.', '13.5 - 17.5 g/dL', 764.54, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (472, 'Urinalysis', 'Sed accumsan felis.', '13.5 - 17.5 g/dL', 946.55, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (473, 'Vitamin D Test', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '3.5 - 5.0', 507.99, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (474, 'Glucose Test', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Normal', 988.07, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (475, 'Electrolyte Panel', 'Quisque ut erat.', '13.5 - 17.5 g/dL', 266.59, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (476, 'Urinalysis', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '13.5 - 17.5 g/dL', 250.85, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (477, 'Glucose Test', 'Nulla tempus.', '13.5 - 17.5 g/dL', 338.38, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (478, 'Glucose Test', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Normal', 358.63, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (479, 'Kidney Function Test', 'Nam nulla.', '70 - 100 mg/dL', 775.28, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (480, 'Electrolyte Panel', 'Ut tellus.', '70 - 100 mg/dL', 252.17, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (481, 'Glucose Test', 'Sed accumsan felis.', '70 - 100 mg/dL', 689.67, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (482, 'Glucose Test', 'Proin risus.', '13.5 - 17.5 g/dL', 878.78, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (483, 'Electrolyte Panel', 'Proin at turpis a pede posuere nonummy.', '13.5 - 17.5 g/dL', 623.31, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (484, 'Urinalysis', 'Aliquam non mauris.', 'Negative', 726.25, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (485, 'Urinalysis', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '3.5 - 5.0', 346.79, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (486, 'Electrolyte Panel', 'Pellentesque eget nunc.', 'Negative', 759.64, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (487, 'Electrolyte Panel', 'Duis ac nibh.', '0.5 - 1.2', 206.16, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (488, 'Electrolyte Panel', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Negative', 860.18, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (489, 'Thyroid Function', 'Duis aliquam convallis nunc.', '0.5 - 1.2', 756.75, 'Serum');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (490, 'Lipid Panel', 'Duis consequat dui nec nisi volutpat eleifend.', '70 - 100 mg/dL', 219.73, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (491, 'Electrolyte Panel', 'Curabitur at ipsum ac tellus semper interdum.', '70 - 100 mg/dL', 65.33, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (492, 'Glucose Test', 'Nam dui.', 'Negative', 736.09, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (493, 'Lipid Panel', 'In congue.', 'Normal', 368.12, 'Tissue');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (494, 'Kidney Function Test', 'Vivamus vestibulum sagittis sapien.', '0.5 - 1.2', 478.46, 'Swab');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (495, 'Lipid Panel', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Normal', 797.75, 'Plasma');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (496, 'Vitamin D Test', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '13.5 - 17.5 g/dL', 150.57, 'Urine');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (497, 'Vitamin D Test', 'Praesent lectus.', '3.5 - 5.0', 906.92, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (498, 'Hemoglobin A1c', 'Integer a nibh.', '70 - 100 mg/dL', 818.72, 'Saliva');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (499, 'Thyroid Function', 'Duis mattis egestas metus.', '70 - 100 mg/dL', 334.63, 'Blood');
insert into LAB_TEST (test_id, test_name, description, normal_range, cost, sample_type) values (500, 'Kidney Function Test', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'Negative', 441.73, 'Swab');
