DROP TABLE IF EXISTS LAB_RESULT;
DROP TABLE IF EXISTS LAB_ORDER_TEST;
DROP TABLE IF EXISTS LAB_ORDER;
DROP TABLE IF EXISTS LAB_TEST;
DROP TABLE IF EXISTS LAB_TECHNICIAN;
DROP TABLE IF EXISTS DIAGNOSTIC_EQUIPMENT;