insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (1, 370, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (2, 933, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (3, 220, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (4, 776, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (5, 853, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (6, 7, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (7, 649, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (8, 763, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (9, 302, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (10, 999, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (11, 632, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (12, 531, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (13, 255, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (14, 929, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (15, 446, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (16, 673, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (17, 369, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (18, 311, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (19, 20, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (20, 511, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (21, 956, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (22, 670, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (23, 809, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (24, 958, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (25, 576, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (26, 997, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (27, 258, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (28, 634, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (29, 646, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (30, 475, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (31, 800, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (32, 13, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (33, 868, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (34, 493, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (35, 784, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (36, 271, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (37, 352, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (38, 326, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (39, 961, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (40, 602, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (41, 132, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (42, 290, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (43, 490, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (44, 371, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (45, 56, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (46, 813, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (47, 682, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (48, 757, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (49, 171, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (50, 821, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (51, 280, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (52, 998, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (53, 268, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (54, 666, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (55, 528, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (56, 435, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (57, 559, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (58, 42, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (59, 614, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (60, 628, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (61, 519, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (62, 207, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (63, 364, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (64, 284, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (65, 915, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (66, 545, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (67, 627, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (68, 959, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (69, 852, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (70, 736, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (71, 601, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (72, 948, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (73, 602, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (74, 296, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (75, 123, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (76, 77, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (77, 559, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (78, 935, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (79, 537, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (80, 453, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (81, 788, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (82, 175, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (83, 584, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (84, 201, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (85, 991, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (86, 370, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (87, 774, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (88, 206, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (89, 243, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (90, 494, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (91, 210, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (92, 659, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (93, 252, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (94, 271, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (95, 639, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (96, 642, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (97, 491, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (98, 891, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (99, 975, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (100, 255, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (101, 681, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (102, 911, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (103, 216, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (104, 659, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (105, 183, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (106, 827, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (107, 44, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (108, 315, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (109, 727, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (110, 676, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (111, 683, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (112, 226, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (113, 746, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (114, 675, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (115, 352, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (116, 406, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (117, 631, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (118, 585, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (119, 935, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (120, 78, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (121, 396, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (122, 988, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (123, 639, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (124, 499, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (125, 72, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (126, 114, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (127, 787, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (128, 42, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (129, 256, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (130, 622, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (131, 18, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (132, 947, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (133, 406, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (134, 983, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (135, 12, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (136, 708, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (137, 519, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (138, 26, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (139, 880, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (140, 986, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (141, 712, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (142, 375, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (143, 966, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (144, 191, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (145, 71, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (146, 810, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (147, 910, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (148, 777, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (149, 371, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (150, 586, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (151, 592, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (152, 937, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (153, 385, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (154, 448, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (155, 749, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (156, 344, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (157, 979, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (158, 900, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (159, 725, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (160, 165, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (161, 833, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (162, 356, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (163, 691, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (164, 763, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (165, 46, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (166, 727, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (167, 72, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (168, 47, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (169, 6, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (170, 530, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (171, 256, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (172, 321, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (173, 712, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (174, 342, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (175, 335, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (176, 797, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (177, 478, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (178, 321, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (179, 323, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (180, 550, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (181, 535, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (182, 601, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (183, 93, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (184, 59, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (185, 809, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (186, 264, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (187, 823, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (188, 880, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (189, 220, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (190, 818, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (191, 895, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (192, 282, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (193, 569, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (194, 155, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (195, 674, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (196, 968, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (197, 177, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (198, 270, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (199, 304, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (200, 39, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (201, 849, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (202, 721, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (203, 945, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (204, 817, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (205, 905, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (206, 989, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (207, 581, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (208, 70, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (209, 532, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (210, 367, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (211, 900, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (212, 891, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (213, 553, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (214, 648, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (215, 42, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (216, 26, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (217, 155, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (218, 551, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (219, 885, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (220, 653, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (221, 807, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (222, 487, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (223, 791, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (224, 315, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (225, 622, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (226, 323, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (227, 719, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (228, 621, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (229, 367, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (230, 878, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (231, 678, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (232, 855, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (233, 215, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (234, 490, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (235, 764, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (236, 422, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (237, 906, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (238, 210, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (239, 221, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (240, 672, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (241, 533, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (242, 35, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (243, 943, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (244, 764, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (245, 545, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (246, 581, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (247, 428, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (248, 206, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (249, 712, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (250, 161, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (251, 929, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (252, 888, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (253, 28, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (254, 542, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (255, 850, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (256, 176, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (257, 559, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (258, 574, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (259, 485, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (260, 394, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (261, 47, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (262, 141, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (263, 415, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (264, 41, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (265, 748, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (266, 464, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (267, 980, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (268, 947, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (269, 931, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (270, 616, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (271, 631, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (272, 769, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (273, 913, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (274, 778, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (275, 624, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (276, 186, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (277, 659, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (278, 707, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (279, 612, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (280, 487, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (281, 915, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (282, 321, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (283, 892, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (284, 326, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (285, 383, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (286, 54, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (287, 716, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (288, 96, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (289, 739, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (290, 776, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (291, 19, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (292, 151, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (293, 494, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (294, 87, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (295, 421, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (296, 156, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (297, 780, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (298, 858, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (299, 790, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (300, 570, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (301, 256, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (302, 942, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (303, 360, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (304, 553, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (305, 191, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (306, 680, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (307, 566, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (308, 384, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (309, 788, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (310, 553, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (311, 846, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (312, 674, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (313, 4, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (314, 478, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (315, 126, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (316, 120, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (317, 713, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (318, 831, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (319, 415, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (320, 836, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (321, 899, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (322, 823, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (323, 9, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (324, 699, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (325, 323, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (326, 857, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (327, 777, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (328, 2, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (329, 801, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (330, 706, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (331, 82, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (332, 696, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (333, 488, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (334, 373, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (335, 11, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (336, 548, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (337, 523, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (338, 329, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (339, 485, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (340, 876, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (341, 472, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (342, 356, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (343, 808, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (344, 252, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (345, 986, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (346, 1, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (347, 347, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (348, 21, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (349, 163, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (350, 808, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (351, 402, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (352, 814, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (353, 852, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (354, 816, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (355, 242, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (356, 250, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (357, 163, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (358, 836, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (359, 237, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (360, 683, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (361, 346, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (362, 815, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (363, 90, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (364, 104, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (365, 270, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (366, 507, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (367, 208, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (368, 838, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (369, 96, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (370, 564, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (371, 854, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (372, 836, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (373, 782, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (374, 721, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (375, 60, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (376, 60, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (377, 33, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (378, 3, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (379, 801, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (380, 799, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (381, 229, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (382, 737, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (383, 360, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (384, 568, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (385, 380, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (386, 992, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (387, 149, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (388, 736, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (389, 194, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (390, 746, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (391, 350, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (392, 639, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (393, 804, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (394, 798, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (395, 320, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (396, 529, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (397, 180, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (398, 303, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (399, 825, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (400, 26, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (401, 252, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (402, 979, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (403, 972, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (404, 80, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (405, 136, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (406, 901, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (407, 218, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (408, 514, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (409, 395, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (410, 553, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (411, 167, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (412, 782, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (413, 630, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (414, 333, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (415, 230, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (416, 920, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (417, 262, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (418, 111, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (419, 527, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (420, 144, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (421, 569, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (422, 679, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (423, 556, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (424, 646, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (425, 863, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (426, 184, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (427, 539, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (428, 25, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (429, 675, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (430, 772, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (431, 893, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (432, 361, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (433, 183, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (434, 72, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (435, 239, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (436, 945, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (437, 372, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (438, 204, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (439, 388, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (440, 314, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (441, 409, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (442, 964, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (443, 242, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (444, 630, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (445, 716, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (446, 429, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (447, 733, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (448, 895, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (449, 193, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (450, 206, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (451, 610, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (452, 376, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (453, 295, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (454, 949, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (455, 233, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (456, 97, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (457, 186, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (458, 859, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (459, 320, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (460, 493, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (461, 896, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (462, 27, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (463, 249, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (464, 350, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (465, 253, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (466, 234, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (467, 650, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (468, 779, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (469, 281, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (470, 943, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (471, 888, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (472, 401, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (473, 807, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (474, 785, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (475, 398, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (476, 496, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (477, 454, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (478, 817, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (479, 881, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (480, 815, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (481, 873, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (482, 204, 'Molecular Biology (MB)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (483, 962, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (484, 368, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (485, 356, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (486, 355, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (487, 741, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (488, 278, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (489, 127, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (490, 106, 'Medical Technologist (MT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (491, 850, 'Phlebotomy Technician (PBT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (492, 523, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (493, 520, 'Cytotechnologist (CT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (494, 780, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (495, 555, 'Clinical Laboratory Technician (CLT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (496, 434, 'Certified Histotechnician (HT)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (497, 880, 'Specialist in Cytogenetics (CG)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (498, 699, 'ASCP Certified');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (499, 264, 'Medical Laboratory Scientist (MLS)');
insert into LAB_TECHNICIAN (technician_id, staff_id, certification) values (500, 520, 'Medical Laboratory Scientist (MLS)');
